# Compiles the data glossary (launch/_work/glossary/build_glossary.py output:
# glossary_ja.tsv / glossary_ko.tsv, src<TAB>zh<TAB>mode<TAB>kind<TAB>conf<TAB>source)
# into translate/src/glossary_data.inc (built into pm_translate: no files to
# install).  Sources and licences: launch/_work/glossary/SOURCES.md (Wikidata
# CC0, hand-curated lists, OpenCC-converted labels).
#
#   py -3 translate/tools/make_glossary_inc.py DIR_WITH_TSVS
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "glossary_data.inc")
BS = chr(92)
QUOTE = chr(34)


def lit(s):
    """A C string literal of s (the file is UTF-8, compiled with /utf-8)."""
    return QUOTE + "".join(BS + c if c in (QUOTE, BS) else c for c in s) + QUOTE


def rows(path):
    for ln in open(path, encoding="utf-8"):
        ln = ln.rstrip("\r\n")
        if not ln or ln.startswith("#"):
            continue
        c = ln.split("\t")
        if len(c) < 4 or c[0] == "src":
            continue
        yield c[0], c[1], c[2], c[3]


def main():
    d = sys.argv[1]
    out = ["// Generated by translate/tools/make_glossary_inc.py from glossary_ja.tsv / glossary_ko.tsv / glossary_en.tsv",
           "// (launch/_work/glossary; sources and licences there: SOURCES.md).  Do not edit.",
           "// {source term, zh-Hant, mode (x whole block / s inside text too / q en: inside text before an amount), kind}"]
    n = 0
    for lang in ("ja", "ko", "en"):
        path = os.path.join(d, "glossary_%s.tsv" % lang)
        out.append("const GlossaryRow kGlossary%s[] = {" % lang.capitalize())
        if not os.path.exists(path) and lang == "en":  # no English list: one empty row (skipped by gAdd)
            out.append('    {"", "", ' + "'x'" + ', ""},')
        for s, z, m, k in (rows(path) if os.path.exists(path) else []):
            out.append("    {%s, %s, '%s', %s}," % (lit(s), lit(z), (m or "x")[0], lit(k)))
            n += 1
        out.append("};")
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    print("wrote", OUT, n, "rows")


if __name__ == "__main__":
    main()
