// Generated by docs/mascot/toutou/export.mjs - do not edit.
// 投投 layer geometry in the art's frame units (layers cover kCanvas; the character is tilted kTilt degrees
// around kPivot, which is also the squash / stretch pivot = bottom centre of the cloud).
#pragma once
namespace pm::video::toutou {
struct Rect { float x, y, w, h; };
struct Phone { float x, y, w, h, rot; };  // centre, size, rotation (deg), before the tilt
constexpr Rect kCanvas{30.f, 38.f, 210.f, 150.f};
constexpr float kTilt = -3.f;
constexpr float kPivotX = 133.f, kPivotY = 166.f;
// Cloud extent (for layout): left, top, right, bottom of the body silhouette.
constexpr Rect kBody{54.f, 50.f, 158.f, 116.f};
enum Pose { kHold, kSleepy, kAsleep };
constexpr Phone kPhone[3] = {
    {221.f, 126.f, 30.f, 48.f, 14.f},  // hold
    {208.f, 150.f, 30.f, 48.f, 34.f},  // sleepy
    {200.f, 174.f, 30.f, 48.f, 80.f},  // asleep
};
constexpr float kPhoneRadius = 7.f, kPhoneBezel = 2.6f;
constexpr float kLayerScale = 4.f;  // layer pixels per frame unit
}  // namespace pm::video::toutou
