// WIC helpers for the status UI: the embedded 投投 (Toutou) mascot layers and
// PNG export.
#pragma once

#include <wincodec.h>
#include <wrl/client.h>

#include <array>
#include <cstdint>
#include <string>
#include <vector>

#include "../res/toutou/toutou_layout.h"

namespace pm::video {

using Microsoft::WRL::ComPtr;

// 投投 Toutou, the original cloud mascot (docs/mascot/toutou, generated by
// export.mjs into res/toutou/*.png and embedded).  Every layer covers the same
// canvas (toutou::kCanvas, in the art's frame units); the renderer composes
// them with Direct2D: cloud, rim light (an alpha mask tinted with the theme
// accent), face per expression, the phone (procedural), the hand holding it
// (per phone pose) and the beam of light (procedural).
class ToutouArt {
public:
    enum Layer {
        Cloud,
        Rim,
        FaceIdle,
        FaceBlink,
        FaceHappy,
        FaceConnecting,
        FaceSurprised,
        FaceSleepy,
        FaceAsleep,
        HandHold,
        HandSleepy,
        HandAsleep,
        kLayers
    };

    // Requires COM on the calling thread.  Returns false if decoding fails
    // (the UI then simply draws without the mascot).
    bool load();
    bool loaded() const { return loaded_; }
    void reset();

    // Part of the canvas a layer covers (frame units; layers are stored
    // cropped to their opaque area).
    struct Placed {
        float x, y, w, h;
    };
    const Placed& placed(Layer l) const { return place_[l]; }
    // The layer resampled (high-quality cubic) for about pxPerUnit pixels per
    // frame unit; quantized so resizing does not rescale on every step (all
    // layers share one cached scale).
    IWICBitmap* scaled(Layer l, float pxPerUnit);
    float quantize(float pxPerUnit) const;

    // Coarse opacity mask over the whole canvas for hit testing (cloud, hand,
    // phone at rest): maskW() x maskH() bytes, 1 where opaque.  Immutable
    // after load().
    const std::vector<uint8_t>& mask() const { return mask_; }
    UINT maskW() const { return maskW_; }
    UINT maskH() const { return maskH_; }

private:
    ComPtr<IWICImagingFactory> wic_;
    std::array<ComPtr<IWICBitmap>, kLayers> src_, cache_;
    std::array<Placed, kLayers> place_{};
    float cacheScale_ = 0;
    bool loaded_ = false;
    std::vector<uint8_t> mask_;
    UINT maskW_ = 0, maskH_ = 0;
};

// Writes 32-bit rows (stride w*4) as a PNG: BGRX -> 24-bit, or straight
// BGRA -> 32-bit with alpha.  Any thread; COM is initialised for the call if
// needed.
bool writePng(const std::wstring& path, const uint8_t* bgrx, UINT w, UINT h, bool alpha = false);

}  // namespace pm::video
